name: build-hello
run-name: Building hello by ${{ github.actor }}
on: [push]
jobs:
  build-the-thing:
    runs-on: macos-12
    steps:
      - uses: pyinstaller/pyinstaller
      - name: Make sure we're on OSX
        run: uname -a
