name: build-hello
run-name: Building ${{ github.project }} by ${{ github.actor }}
on: [push]
jobs:
  build-the-thing:
    runs-on: ubuntu-latest #macos-12
    steps:
      - name: Make sure we're on OSX
        run: uname -a
      - uses: actions/checkout@v3
      - name: Run the thing
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - uses: pyinstaller/pyinstaller@latest
      - run: python hello.py

