name: build-hello
run-name: Building hello by ${{ github.actor }}
on: [push]
jobs:
  build-the-thing:
    runs-on: macos-12
    steps:
      - run: pip install pyinstaller
      - run: pyinstaller --onefile hello.py
