name: build-hello
run-name: Building hello by ${{ github.actor }}
on: [push]
jobs:
  build-the-thing:
    runs-on: macos-12
    steps:
      - name: Make sure we're on OSX
        run: uname -a
      - name: Run the thing
        with:
          python-version: '3.x'
        run: python hello.py
