name: build-hello
run-name: Building hello by ${{ github.actor }}
on: [push]
jobs:
  build-the-thing:
    runs-on: macos-12
    steps:
      - run: pip3 install pyinstaller
      - run: ls /Library/Frameworks/Python.framework/Versions/3.11/bin/
      - run: /Library/Frameworks/Python.framework/Versions/3.11/bin/pyinstaller --onefile hello.py
